<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>ca55db27-f68c-4036-80ed-84f6a61b6cb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button_Button__QGZ2g.Button_Button--text__JelYA.ContactPopUp__Button__Kmtt4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[4]/div/form/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc3ed4d8-4ea4-4356-99d2-829edc512562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_Button__QGZ2g Button_Button--text__JelYA ContactPopUp__Button__Kmtt4</value>
      <webElementGuid>ec6e67b2-9115-464a-8732-47f0623ac5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>bae6cfcb-5b9d-4ec3-9cb0-72d26911ef60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/div[@class=&quot;ContactPopUp__Wrapper__APn0H ContactPopUp__Open__kiaOF&quot;]/div[@class=&quot;ContactPopUp__Container__QvfcT container&quot;]/form[1]/button[@class=&quot;Button_Button__QGZ2g Button_Button--text__JelYA ContactPopUp__Button__Kmtt4&quot;]</value>
      <webElementGuid>02fd649e-9163-45fb-a671-0b8874983264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[4]/div/form/button</value>
      <webElementGuid>350807d2-3f3f-4100-a90d-1fbb367d1ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Development'])[2]/following::button[1]</value>
      <webElementGuid>383d64a6-d08a-4d8c-bd7c-00de80b6c056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MadeIndonesia'])[1]/following::button[1]</value>
      <webElementGuid>c93b4e92-51e0-4a58-9265-cbda169e804e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to home'])[1]/preceding::button[1]</value>
      <webElementGuid>4137b366-bed2-4ff6-9ecc-f350badafc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>eecb142e-ff0d-4494-b7d9-60908dc50f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>607bb301-f8cc-41c5-ada4-707243c633e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>9472d759-5ab1-4a9c-8c65-c65eb3bc590e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
