<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select_css-czldi3</name>
   <tag></tag>
   <elementGuidId>c52c402d-82b1-49c1-bc5c-cac8a46b9c65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[4]/div/form/div[2]/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7083491f-67f5-42ae-bca3-3ce3704b6e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-czldi3</value>
      <webElementGuid>612d5a5a-6797-4f27-8e88-b1219027dd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/div[@class=&quot;ContactPopUp__Wrapper__APn0H ContactPopUp__Open__kiaOF&quot;]/div[@class=&quot;ContactPopUp__Container__QvfcT container&quot;]/form[1]/div[@class=&quot;ContactPopUp__InputGroup__KegMW&quot;]/div[@class=&quot;CustomSelect__Wrapper__fAMBd&quot;]/div[@class=&quot;css-1iujzst-container&quot;]/div[@class=&quot;css-19qk4o3-control&quot;]/div[@class=&quot;css-1igrgh1&quot;]/div[@class=&quot;css-czldi3&quot;]</value>
      <webElementGuid>7d1e6171-8f12-42b6-8f10-549ab5b9830c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[4]/div/form/div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>4b11f28f-1f16-459c-b63f-440baeca5b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/following::div[1]</value>
      <webElementGuid>36ab5597-2381-45b2-9031-58f637624930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MadeIndonesia'])[1]/following::div[16]</value>
      <webElementGuid>f2c09384-4997-4901-a93f-845935a1848e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design'])[2]/preceding::div[3]</value>
      <webElementGuid>2c7d818c-bc42-4de0-9b27-a0d350d710ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Development'])[2]/preceding::div[4]</value>
      <webElementGuid>900e8795-5a92-462b-8af9-f41d1d445367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>7042fb66-5741-4815-b41c-e2d37d4034e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
