<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Development</name>
   <tag></tag>
   <elementGuidId>1deb28a5-b0e1-4fa5-93b6-5b7112518701</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73a7b1ce-da2d-406a-ab6d-7c27d7706484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-synpnt-option</value>
      <webElementGuid>cc94e6e9-911d-4b65-ab29-ec25aa8c8afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9bceed5a-3535-4018-9b55-73903009fbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-1</value>
      <webElementGuid>4f10104b-e280-4ac2-a73b-6b7695a9f520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ac2a33a3-ef6b-4e0a-9cfa-67d9e404d5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Development</value>
      <webElementGuid>bdbcb120-4691-4b55-bb1f-832079f9d083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-1&quot;)</value>
      <webElementGuid>b5aa5c97-ae3b-4aeb-81c5-60ac1dd951e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-1']</value>
      <webElementGuid>03a45186-60a2-4d77-88f7-a930e29aa0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div/div[2]</value>
      <webElementGuid>45f83ff0-2ab8-44d7-b819-0af80218ec3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design'])[2]/following::div[1]</value>
      <webElementGuid>7c25f1e2-8d67-4fc9-ab10-29a94b497738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/following::div[7]</value>
      <webElementGuid>871b0a31-1c1a-453c-97cc-d9b59fd57844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data entry'])[3]/preceding::div[1]</value>
      <webElementGuid>a5c9b98e-de02-4eb6-9a23-5bf3d6574f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video marketing'])[2]/preceding::div[2]</value>
      <webElementGuid>15275844-0221-46ef-8324-4a154cbd0a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>3617f5cc-6932-4442-ac00-c275b4e95454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-1' and (text() = 'Development' or . = 'Development')]</value>
      <webElementGuid>19183b5d-b105-407c-a5cb-7130297fc3ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
