<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MadeIndonesia_email</name>
   <tag></tag>
   <elementGuidId>0b69bd73-e9d8-40e1-afa9-0cc506e5ee91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b123364-1a6c-4f63-9ff2-e1c31495cce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>363691a4-48c9-4d14-b13a-008c3617e7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/div[@class=&quot;ContactPopUp__Wrapper__APn0H ContactPopUp__Open__kiaOF&quot;]/div[@class=&quot;ContactPopUp__Container__QvfcT container&quot;]/form[1]/div[@class=&quot;ContactPopUp__InputGroup__KegMW&quot;]/div[@class=&quot;Input__Wrapper__65Rk7&quot;]/input[1]</value>
      <webElementGuid>7ebe9437-f46b-4cb6-87d2-ff7d637ef3ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>3c0211f9-b7cb-4b04-8db5-3afb92c2e23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[4]/div/form/div/div[2]/input</value>
      <webElementGuid>d22a0dac-eac8-4625-9948-ac4d7fa6e3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5e3a4afb-9060-4729-8301-5c81e80c3f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email']</value>
      <webElementGuid>629f3c5d-51ed-47a6-b0a1-d11023977977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
