<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MadeIndonesia_companyName</name>
   <tag></tag>
   <elementGuidId>83d1f247-89e7-406c-8557-bb9a52c474c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;companyName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='companyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fa78d91-7d0d-4329-9d78-af2d71222e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyName</value>
      <webElementGuid>80031489-2890-41c9-99f7-d848db34dbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/div[@class=&quot;ContactPopUp__Wrapper__APn0H ContactPopUp__Open__kiaOF&quot;]/div[@class=&quot;ContactPopUp__Container__QvfcT container&quot;]/form[1]/div[@class=&quot;ContactPopUp__InputGroup__KegMW&quot;]/div[@class=&quot;Input__Wrapper__65Rk7&quot;]/input[1]</value>
      <webElementGuid>1f8d3ac1-21cd-4657-9758-028eed5beeb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='companyName']</value>
      <webElementGuid>4314be59-da21-476c-adcb-3e0e6e20bbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[4]/div/form/div[2]/div/input</value>
      <webElementGuid>1127dcb7-9b6a-4da1-9017-a7f94bde3dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0689f2ea-c02a-4638-9bb0-850c4662c13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'companyName']</value>
      <webElementGuid>f00a7454-2291-46a9-b462-44ce9f7bbace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
